[package]
name = "puzzles-aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
scan_fmt = "0.2.6"
ndarray = "0.16.1"
itertools = "0.13.0"
regex = "1.11.1"
gridly = "0.9.1"
gridly_grids = "0.5.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
assertables = "9"